export const SUPPORTED_CHAINS = {
    SEPOLIA: 11155111,
    ARBITRUM_SEPOLIA: 421614,
    BASE_SEPOLIA: 84532,
    OPTIMISM_SEPOLIA: 11155420,
    POLYGON_AMOY: 80002,
} as const;

export const CHAIN_NAMES: Record<number, string> = {
    [SUPPORTED_CHAINS.SEPOLIA]: 'Sepolia',
    [SUPPORTED_CHAINS.ARBITRUM_SEPOLIA]: 'Arbitrum Sepolia',
    [SUPPORTED_CHAINS.BASE_SEPOLIA]: 'Base Sepolia',
    [SUPPORTED_CHAINS.OPTIMISM_SEPOLIA]: 'Optimism Sepolia',
    [SUPPORTED_CHAINS.POLYGON_AMOY]: 'Polygon Amoy',
};

export const TESTNET_CHAINS = [
    { id: SUPPORTED_CHAINS.SEPOLIA, name: CHAIN_NAMES[SUPPORTED_CHAINS.SEPOLIA] },
    { id: SUPPORTED_CHAINS.ARBITRUM_SEPOLIA, name: CHAIN_NAMES[SUPPORTED_CHAINS.ARBITRUM_SEPOLIA] },
    { id: SUPPORTED_CHAINS.BASE_SEPOLIA, name: CHAIN_NAMES[SUPPORTED_CHAINS.BASE_SEPOLIA] },
    { id: SUPPORTED_CHAINS.OPTIMISM_SEPOLIA, name: CHAIN_NAMES[SUPPORTED_CHAINS.OPTIMISM_SEPOLIA] },
    { id: SUPPORTED_CHAINS.POLYGON_AMOY, name: CHAIN_NAMES[SUPPORTED_CHAINS.POLYGON_AMOY] },
];